---
- name: 主机基本设置
  hosts: deployment_host
  gather_facts: "{{ set_gather_facts | default(True) }}"
  user: root
  pre_tasks:
    - name: 检测支持的操作系统（目前是基于centos7 安装配置其它系统咱不支持）
      assert:
        that:
          - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
        msg: "系统仅支持 CentOS 7 (WIP)"

    - name: 检测内核版本（最新的内核）
      fail:
        msg: >
          错误的内核版本
          [ {{ ansible_kernel }} < {{ hadoop_host_required_kernel }} ]
          在继续之前解决这个问题（yum update 升级内核）.
      when:
         - ansible_kernel is version_compare(hadoop_host_required_kernel, '<')
         - inventory_hostname in groups['cluster_host']

    - name: 检测离线包
      shell: >-
        ls /tmp  |egrep -e "{{ hadoop_local_packges_name | join('|')  }}"
      args:
        executable: /bin/bash
        warn: no
      changed_when: false
      failed_when: false
      register: _packges_exists
        
    - name: 检测离线包在本地/tmp 下是否完整
      assert:
        that:
          -  hadoop_local_packges_name | difference(_packges_exists.stdout_lines) | length == 0
        msg: "离线包不完整 请上传离线包到本地/tmp/目录下"

  roles:
    - role: "local_repo"
  vars_files: []

  post_tasks:
    - name: 重启服务
      service:
        name: "{{ web_service_name }}" 
        state: restarted
        enabled: yes

